heavenly_stems = ['jia',
                  'yi',
                  'bing',
                  'ding',
                  'wu',
                  'ji',
                  'geng',
                  'xin',
                  'ren', 
                  'gui']

elements = ['wood',
            'wood',
            'fire',
            'fire',
            'earth',
            'earth',
            'metal',
            'metal',
            'water',
            'water']

earthly_branches = ['zi',
                    'chou',
                    'yin',
                    'mao',
                    'chen',
                    'si',
                    'wu',
                    'wei',
                    'shen',
                    'you',
                    'xu',
                    'hai']

zodiac = [ 'rat', 
           'ox', 
           'tiger', 
           'rabbit', 
           'dragon', 
           'snake', 
           'horse', 
           'goat',
           'monkey',
           'rooster',
           'dog',
           'pig']
